apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:1.20
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.5
            memory: 100Mi
          limits:
            cpu: 0.5
            memory: 100Mi
      - image: hello-world
        name: hello
        ports:
        - containerPort: 80
